name: Build Container Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: colinbut/terraform-build-container
          tag_with_ref: true

      - name: push to github container registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
          registry: docker.pkg.github.com
          repository: colinbut1/terraform-build-container/terraform-build-container
          tag_with_ref: true
