name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v2
      
      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: 'terraform'
      
      - name: run tflint
        uses: actions/@notrenderfarm/tflint-action@v1
        with:
          directory: 'terraform'

      - name: run tfsec
        uses: triat/terraform-security-scan@v2.0.2
