name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: colinbut/terraform-testing-strategy:3.0.0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: terraform validate
        run: terraform validate
      
      - name: run tflint
        run: tflint terraform

      - name: run tfsec
        run: tfsec .
